# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["supreet@skyfire.xyz"]
description = "Batch charging of KYA+PAY tokens"
language = "javascript"
manifest_version = 3
name = "fastly_compute_with_KV_batch_charging"
service_id = "VQ14GHWSSaNF0LlEVe1OSC"

[local_server]

  [local_server.backends]

    [local_server.backends.real_estate_protected_website]
      override_host = "demo-real-estate-prv4.onrender.com"
      url = "https://demo-real-estate-prv4.onrender.com"

    [local_server.backends.skyfire_be]
      override_host = "api-qa.skyfire.xyz"
      url = "https://api-qa.skyfire.xyz"

    [local_server.backends.upstash]
      url = "https://sure-seasnail-19324.upstash.io"

  [local_server.kv_stores]
    first_KV_batch_charging = { file = './kv_data_example/example_kv_store.json', format = 'json' }

[setup]
  [setup.backends]
    [setup.backends.real_estate_protected_website]
      address = "demo-real-estate-prv4.onrender.com"
      port = 443


[scripts]
  build = "npm run build"
  post_init = "npm install"
